[package]
name = "fintrack"
version = "0.1.0"
authors = ["Hasan Ali <git@hasali.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.6.2", features = ["attributes"] }
handlebars = { version = "3.3.0", features = ["dir_source"] }
serde = "1.0.114"
serde_json = "1.0.57"
tide = "0.13.0"
